apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: renice-sl-ingress
  namespace: renice-sl
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: renice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: renice-sl-web
                port:
                  number: 3000
