server:
  port: 8080
  mode: dev

database:
  host: postgres
  port: 5432
  user: renice
  password: 000000
  dbname: renice_sl
  sslmode: false

redis:
  host: redis
  port: 6379
  password: 000000
  db: 0
  pool_size: 20