apiVersion: batch/v1
kind: Job
metadata:
  name: renice-sl-migrate
  namespace: renice-sl
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/ice-awa/renice-sl-server:v0.0.4
          command: ["./migrate", "up"]
          envFrom:
            - configMapRef:
                name: renice-sl-config
            - secretRef:
                name: renice-sl-secret