global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "renice-sl-api"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - renice-sl-api:8080
  - job_name: "renice-sl-worker"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - renice-sl-worker:8080