apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renice-sl-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ICE-awa/renice-sl.git
    targetRevision: main
    path: deploy/k8s/overlays/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: renice-sl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true