name: Docker

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/ice-awa/renice-sl-server:${{ github.ref_name }}
            ghcr.io/ice-awa/renice-sl-server:latest
      - uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/ice-awa/renice-sl-web:${{ github.ref_name }}
            ghcr.io/ice-awa/renice-sl-web:latest

  deploy:
    runs-on: [ self-hosted, linux, renice-sl ]
    needs: build
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          kubectl set image deployment/renice-sl-server \
            renice-sl-server=ghcr.io/ice-awa/renice-sl-server:${{ github.ref_name }} \
            -n renice-sl
          
          kubectl set image deployment/renice-sl-web \
            renice-sl-web=ghcr.io/ice-awa/renice-sl-web:${{ github.ref_name }} \
            -n renice-sl
          
          kubectl rollout status deployment/renice-sl-api -n renice-sl
          kubectl rollout status deployment/renice-sl-worker -n renice-sl
          kubectl rollout status deployment/renice-sl-web -n renice-sl